### ISSUE TITLE
From gallery : No such file or directory

### ISSUE THREAD

**Issue by QPAYRE** [sawankumarbundelkhandi/edge_detection#120]
Just ran your example and got this error and had pretty much the same on my project.

Only if I pick from the gallery on iOs (Didn't try on android)

```💪 Running with sound null safety 💪

An Observatory debugger and profiler on iPhone 14 Pro Max is available at: http://127.0.0.1:52355/Am-AXM7VDfQ=/
The Flutter DevTools debugger and profiler on iPhone 14 Pro Max is available at: http://127.0.0.1:9102?uri=http://127.0.0.1:52355/Am-AXM7VDfQ=/
flutter: /Users/quentinpayre/Library/Developer/CoreSimulator/Devices/B82FFF0C-19CC-4BA0-ABC2-9A29F6946FF7/data/Containers/Data/Application/62A6CEC7-5C81-4888-B8AE-E29E6588BC8E/Library/Application Support/1675089091.jpeg : _imagePath
flutter: success: true

══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following PathNotFoundException was thrown resolving an image codec:
Cannot retrieve length of file, path =
'/Users/quentinpayre/Library/Developer/CoreSimulator/Devices/B82FFF0C-19CC-4BA0-ABC2-9A29F6946FF7/data/Containers/Data/Application/62A6CEC7-5C81-4888-B8AE-E29E6588BC8E/Library/Application
Support/1675089091.jpeg' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack:
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:372:7)
<asynchronous suspension>
#2      FileImage._loadAsync (package:flutter/src/painting/image_provider.dart:998:31)
<asynchronous suspension>

Path:
/Users/quentinpayre/Library/Developer/CoreSimulator/Devices/B82FFF0C-19CC-4BA0-ABC2-9A29F6946FF7/data/Containers/Data/Application/62A6CEC7-5C81-4888-B8AE-E29E6588BC8E/Library/Application
Support/1675089091.jpeg
════════════════════════════════════════════════════════════════════════════════════════════════════```

**Comment by jason45992** [comment]
same here

**Comment by jason45992** [comment]
Try using this: https://pub.dev/packages/document_scanner_flutter
Having same functions

**Comment by QPAYRE** [comment]
I already tried it and move to this package because on android when you pick an image from the gallery the app literally crash..

**Comment by rsanjuan87** [comment]
> Try using this: https://pub.dev/packages/document_scanner_flutter Having same functions

but have edge detection?

**Comment by rsanjuan87** [comment]
https://github.com/sawankumarbundelkhandi/edge_detection/issues/109
same bug

**Comment by Niko-by** [comment]
@rsanjuan87 @sawankumarbundelkhandi 
Can you please tell me when these changes will appear on pub.dev?

**Comment by sawankumarbundelkhandi** [comment]
I will publish it in some days. Meanwhile, you can use it directly from Github like this

In pubspec, specify dependency like below

edge_detection: 
   git:
      url: git://github.com/sawankumarbundelkhandi/edge_detection.git

Check git dependency section here for more information - https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by aniket-github** [comment]
are the changes published on pub.dev?
@sawankumarbundelkhandi

**Comment by sawankumarbundelkhandi** [comment]
it's not yet published on pub.dev. please use like this for now - https://github.com/sawankumarbundelkhandi/edge_detection/issues/120#issuecomment-1458253331
