### ISSUE TITLE
I don't know why I get this

### ISSUE THREAD

**Issue by JoseLuisGit** [sawankumarbundelkhandi/edge_detection#13]
Hi, I get this when I'm debugging and I don't really know what it is

```
I/etectionexample( 2931): type=1400 audit(0.0:6353): avc: denied { connectto } for path="/dev/socket/fwmarkd" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1
I/etectionexample( 2931): type=1400 audit(0.0:6354): avc: denied { write } for name="example" dev="sdb3" ino=91026 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=1
I/etectionexample( 2931): type=1400 audit(0.0:6355): avc: denied { add_name } for name="build" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=1
I/etectionexample( 2931): type=1400 audit(0.0:6356): avc: denied { create } for name="build" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=dir permissive=1
I/etectionexample( 2931): type=1400 audit(0.0:6359): avc: denied { create } for name="LICENSE" scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=file permissive=1
I/etectionexample( 2931): type=1400 audit(0.0:6360): avc: denied { write open } for path="/data/data/com.sample.edgedetectionexample/code_cache/exampleXHTZNW/example/build/flutter_assets/LICENSE" dev="sdb3" ino=91030 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:system_data_file:s0:c512,c768 tclass=file permissive=1
D/OpenCV/StaticHelper( 2931): Trying to get library list
E/OpenCV/StaticHelper( 2931): OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper( 2931): Library list: ""
D/OpenCV/StaticHelper( 2931): First attempt to load libs
D/OpenCV/StaticHelper( 2931): Trying to init OpenCV libs
D/OpenCV/StaticHelper( 2931): Trying to load library opencv_java3
D/OpenCV/StaticHelper( 2931): Cannot load library "opencv_java3"
W/System.err( 2931): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sample.edgedetectionexample-8YSfnzQZjMlgAIhGsiNrXA==/base.apk"],nativeLibraryDirectories=[/data/app/com.sample.edgedetectionexample-8YSfnzQZjMlgAIhGsiNrXA==/lib/x86, /data/app/com.sample.edgedetectionexample-8YSfnzQZjMlgAIhGsiNrXA==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]] couldn't find "libopencv_java3.so"

W/System.err( 2931): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
W/System.err( 2931): 	at java.lang.System.loadLibrary(System.java:1657)
W/System.err( 2931): 	at org.opencv.android.StaticHelper.loadLibrary(StaticHelper.java:64)
W/System.err( 2931): 	at org.opencv.android.StaticHelper.initOpenCVLibs(StaticHelper.java:95)
W/System.err( 2931): 	at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:39)
W/System.err( 2931): 	at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:102)
W/System.err( 2931): 	at com.sample.edgedetection.scan.ScanActivity.prepare(ScanActivity.kt:37)
W/System.err( 2931): 	at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:16)
W/System.err( 2931): 	at android.app.Activity.performCreate(Activity.java:6975)
W/System.err( 2931): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
W/System.err( 2931): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
W/System.err( 2931): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
W/System.err( 2931): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/System.err( 2931): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
W/System.err( 2931): 	at android.os.Handler.dispatchMessage(Handler.java:105)
W/System.err( 2931): 	at android.os.Looper.loop(Looper.java:164)
W/System.err( 2931): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
W/System.err( 2931): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 2931): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
W/System.err( 2931): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
D/OpenCV/StaticHelper( 2931): First attempt to load libs fails
I/ScanActivity( 2931): loading opencv error, exit

```

This does not let me use the library. I hope you can help me

**Comment by kalismeras61** [comment]
remove your app and try again.

**Comment by sawankumarbundelkhandi** [comment]
It's related to OpenCV **.so** files 

This might help - https://stackoverflow.com/questions/37180378/android-opencv-error-cannot-load-info-library-for-opencv

**Comment by JoseLuisGit** [comment]
thank you for your answers
