### ISSUE TITLE
Android crash on cancel pick image from gallery

### ISSUE THREAD

**Issue by AhmadHusein5853** [sawankumarbundelkhandi/edge_detection#162]
- By picking an image from the gallery, the user is requested to pick an action (Gallery/Photos).
- If the user cancels this Intent, then the camera is still paused.
- By clicking the camera button to capture a photo, then the app get crashed with the following trace.

```
I/ScanPresenter( 6058): try to focus
D/AndroidRuntime( 6058): Shutting down VM
E/AndroidRuntime( 6058): FATAL EXCEPTION: main
E/AndroidRuntime( 6058): Process: com.sample.edgedetectionexample, PID: 6058
E/AndroidRuntime( 6058): java.lang.RuntimeException: autoFocus failed
E/AndroidRuntime( 6058): 	at android.hardware.Camera.native_autoFocus(Native Method)
E/AndroidRuntime( 6058): 	at android.hardware.Camera.autoFocus(Camera.java:1341)
E/AndroidRuntime( 6058): 	at com.sample.edgedetection.scan.ScanPresenter.shut(ScanPresenter.kt:100)
E/AndroidRuntime( 6058): 	at com.sample.edgedetection.scan.ScanActivity.prepare$lambda$0(ScanActivity.kt:51)
E/AndroidRuntime( 6058): 	at com.sample.edgedetection.scan.ScanActivity.$r8$lambda$kwZnZTmSrrLKlrcL9-Dc10SODxI(Unknown Source:0)
E/AndroidRuntime( 6058): 	at com.sample.edgedetection.scan.ScanActivity$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
E/AndroidRuntime( 6058): 	at android.view.View.performClick(View.java:8043)
E/AndroidRuntime( 6058): 	at android.view.View.performClickInternal(View.java:8020)
E/AndroidRuntime( 6058): 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
E/AndroidRuntime( 6058): 	at android.view.View$PerformClick.run(View.java:31850)
E/AndroidRuntime( 6058): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 6058): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6058): 	at android.os.Looper.loopOnce(Looper.java:230)
E/AndroidRuntime( 6058): 	at android.os.Looper.loop(Looper.java:319)
E/AndroidRuntime( 6058): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/AndroidRuntime( 6058): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6058): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/AndroidRuntime( 6058): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
I/Process ( 6058): Sending signal. PID: 6058 SIG: 9

```
https://github.com/sawankumarbundelkhandi/edge_detection/assets/74105989/375181d2-7755-41b4-b79e-edbd3b2d09fd

**Comment by sagar-doshaheen** [comment]
Is this published on `pub.dev`? @sawankumarbundelkhandi.

**Comment by sawankumarbundelkhandi** [comment]
I will publish it later. You can use it via git directly for now.
