### ISSUE TITLE
Application gets crashed as soon as the edge_detection method is initiated in flutter.

### ISSUE THREAD

**Issue by Appstute-Aditya** [sawankumarbundelkhandi/edge_detection#25]
**Application gets crashed as soon as the edge_detection method is initiated in flutter.**

app/build.gradle :- 
compileSdkVersion 28
minSdkVersion 21
targetSdkVersion 28

android/build.gradle :-
 dependencies added -          
classpath 'com.android.tools.build:gradle:3.6.3'
 classpath 'com.google.gms:google-services:4.3.3'

Android.manifest :- 
<activity>
 android:name=".MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|
density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:theme="@style/LaunchTheme"
            android:usesCleartextTraffic="true"
            android:windowSoftInputMode="adjustResize">
</activity>

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.dev, PID: 14487
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.dev/com.sample.edgedetection.scan.ScanActivity}: android.view.InflateException: Binary XML file line #17 in com.test.dev:layout/abc_screen_toolbar: Binary XML file line #17 in com.test.dev:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3477)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
     Caused by: android.view.InflateException: Binary XML file line #17 in com.test.dev:layout/abc_screen_toolbar: Binary XML file line #17 in com.test.dev:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
     Caused by: android.view.InflateException: Binary XML file line #17 in com.test.dev:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
     Caused by: java.lang.ClassNotFoundException: androidx.appcompat.widget.ActionBarOverlayLayout
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:749)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at com.sample.edgedetection.base.BaseActivity.onCreate(BaseActivity.kt:15)
        at android.app.Activity.performCreate(Activity.java:7817)
        at android.app.Activity.performCreate(Activity.java:7806)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1328)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3452)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3620)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:7617)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: androidx.appcompat.widget.ActionBarOverlayLayout
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 28 more
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/NestedScrollingParent3;
        	... 28 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.NestedScrollingParent3" on path: DexPathList[[zip file "/data/app/com.test.dev-w8KbJf7juztB_q3NicCDsQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.test.dev-w8KbJf7juztB_q3NicCDsQ==/lib/arm64, /data/app/com.test.dev-w8KbJf7juztB_q3NicCDsQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 28 more

Also it shows error at BaseActivity.kt setContentView(provideContentViewId()).

**Comment by sawankumarbundelkhandi** [comment]
If it's open source share the repo link please.
