### ISSUE TITLE
Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_1513.jpeg: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by Hesamedin** [sawankumarbundelkhandi/edge_detection#33]
Hi, I am using the latest version of this library.
This is my code which is based on the sample.
```
void _runEdgeDetection() async {
    print('Running EdgeDetection...');
    String path = '';
    try {
      path = await EdgeDetection.detectEdge;
      print('The saved image path is: $path');
    } on PlatformException catch (e) {
      print('Failed to get cropped image path');
      print(e.message);
    } catch (e) {
      print(e);
    }
  }
```
After running the code on my device, Camera displays, I accept two permission it requests for, take a picture, crop it and once I click on the done button then the app crashes. When I check my internal files, I confirm there is no such a folder.

```
I/PaperProcessor(25043): crop finish
I/PaperProcessor(25043): cropped picture: Mat [ 1035*1464*CV_8UC4, isCont=true, isSubmat=false, nativeObj=0x7bc9076da0, dataAddr=0x7b3e489c80 ]
D/ViewRootImpl@30f3618[CropActivity](25043): ViewPostIme pointer 0
D/ViewRootImpl@30f3618[CropActivity](25043): ViewPostIme pointer 1
D/AndroidRuntime(25043): Shutting down VM
E/AndroidRuntime(25043): FATAL EXCEPTION: main
E/AndroidRuntime(25043): Process: com.atco.techne, PID: 25043
E/AndroidRuntime(25043): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(25043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:506)
E/AndroidRuntime(25043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/AndroidRuntime(25043): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(25043): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/AndroidRuntime(25043): 	... 1 more
E/AndroidRuntime(25043): Caused by: java.io.FileNotFoundException: /storage/emulated/0/smart_scanner/crop_1884.jpeg: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(25043): 	at libcore.io.IoBridge.open(IoBridge.java:496)
E/AndroidRuntime(25043): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
E/AndroidRuntime(25043): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
E/AndroidRuntime(25043): 	at com.sample.edgedetection.crop.CropPresenter.save(CropPresenter.kt:129)
E/AndroidRuntime(25043): 	at com.sample.edgedetection.crop.CropActivity.onOptionsItemSelected(CropActivity.kt:55)
E/AndroidRuntime(25043): 	at android.app.Activity.onMenuItemSelected(Activity.java:4182)
E/AndroidRuntime(25043): 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
E/AndroidRuntime(25043): 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:196)
E/AndroidRuntime(25043): 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
E/AndroidRuntime(25043): 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:888)
E/AndroidRuntime(25043): 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
E/AndroidRuntime(25043): 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
E/AndroidRuntime(25043): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
E/AndroidRuntime(25043): 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
E/AndroidRuntime(25043): 	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
E/AndroidRuntime(25043): 	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
E/AndroidRuntime(25043): 	at android.view.View.performClick(View.java:7869)
E/AndroidRuntime(25043): 	at android.widget.TextView.performClick(TextView.java:14958)
E/AndroidRuntime(25043): 	at android.view.View.performClickInternal(View.java:7838)
E/AndroidRuntime(25043): 	at android.view.View.access$3600(View.java:886)
E/AndroidRuntime(25043): 	at android.view.View$PerformClick.run(View.java:29362)
E/AndroidRuntime(25043): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(25043): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(25043): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(25043): 	at android.app.ActivityThread.main(ActivityThread.java:8125)
E/AndroidRuntime(25043): 	... 3 more
E/AndroidRuntime(25043): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/AndroidRuntime(25043): 	at libcore.io.Linux.open(Native Method)
E/AndroidRuntime(25043): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(25043): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
E/AndroidRuntime(25043): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
E/AndroidRuntime(25043): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8002)
E/AndroidRuntime(25043): 	at libcore.io.IoBridge.open(IoBridge.java:482)
E/AndroidRuntime(25043): 	... 27 more
I/Process (25043): Sending signal. PID: 25043 SIG: 9
Lost connection to device.
```

**Comment by Hesamedin** [comment]
Shoot, the problem was I had changed compileSdkVersion and tragetSdk to be 30 while I was testing on API 28.
Super misleading error.

**Comment by nikolaychernov** [comment]
This really shouldn't be closed, Google Play will require updates to have targerSdk 29+ from 2 November 2020 https://developer.android.com/distribute/best-practices/develop/target-sdk#pre10.
