### ISSUE TITLE
Camera does not work on Android Tablet with android-arm64  • Android 9 (API 28)

### ISSUE THREAD

**Issue by CellCS** [sawankumarbundelkhandi/edge_detection#35]
Google pixel works, but tablet does not work

```
E/flutter (16778): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument(s) (path): Must not be null
E/flutter (16778): #0      ArgumentError.checkNotNull (dart:core/errors.dart:194:27)
E/flutter (16778): #1      _File._checkNotNull (dart:io/file_impl.dart:641:19)
E/flutter (16778): #2      new _File (dart:io/file_impl.dart:205:17)
E/flutter (16778): #3      new File (dart:io/file.dart:250:18)
E/flutter (16778): #4      DFcamera.getImage (package:sources/dfcamera/dfcamera.dart:48:19)
E/flutter (16778): <asynchronous suspension>
E/flutter (16778): #5      _SendPageState._openCamera (package:sources/dfsources.dart:86:22)
E/flutter (16778): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (16778): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (16778): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (16778): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (16778): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (16778): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (16778): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (16778): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (16778): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (16778): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (16778): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (16778): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (16778): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (16778): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (16778): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (16778): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (16778): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (16778): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (16778): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (16778): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (16778): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (16778): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (16778): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
E/flutter (16778): 
I/ScanPresenter(16778): camera null
```

![androidtablet-issue](https://user-images.githubusercontent.com/16886624/93790163-ba0f8400-fc00-11ea-9834-e1952722afd8.png)

**Comment by CellCS** [comment]
Fix with handle camera error.

![image](https://user-images.githubusercontent.com/16886624/109917787-e3d6d780-7c83-11eb-838a-44bfa2a256be.png)

**Comment by sawankumarbundelkhandi** [comment]
Closing the issue as I have merged your PR.

Will release a new version of plugin.
