### ISSUE TITLE
Exception: java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by agent515** [sawankumarbundelkhandi/edge_detection#41]
I copied the required OpenCV folders in the project. When I started the application, I stumbled upon the error below.
It is pointing to Camera.java which is a native implementation, invoked by initCamera in ScanPresenter.kt.

@sawankumarbundelkhandi  Can you suggest a solution?

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Waiting for Android SDK built for x86 to report its views...
D/EGL_emulation( 9477): eglMakeCurrent: 0xe5cc12a0: ver 2 0 (tinfo 0xda884fd0)
D/eglCodecCommon( 9477): setVertexArrayObject: set vao to 0 (0) 1 0
Debug service listening on ws://127.0.0.1:60847/6OLSB5QpglE=/ws
Syncing files to device Android SDK built for x86...
W/ActivityThread( 9477): handleWindowVisibility: no activity for token android.os.BinderProxy@38be9b7
W/om.pixeleye.ap( 9477): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/om.pixeleye.ap( 9477): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/OpenCV/StaticHelper( 9477): Trying to get library list
E/OpenCV/StaticHelper( 9477): OpenCV error: Cannot load info library for OpenCV
D/OpenCV/StaticHelper( 9477): Library list: ""
D/OpenCV/StaticHelper( 9477): First attempt to load libs
D/OpenCV/StaticHelper( 9477): Trying to init OpenCV libs
D/OpenCV/StaticHelper( 9477): Trying to load library opencv_java3
D/OpenCV/StaticHelper( 9477): Library opencv_java3 loaded
D/OpenCV/StaticHelper( 9477): First attempt to load libs is OK
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477): General configuration for OpenCV 3.4.3 =====================================
I/OpenCV/StaticHelper( 9477):   Version control:               3.4.3
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Platform:
I/OpenCV/StaticHelper( 9477):     Timestamp:                   2018-08-29T10:32:02Z
I/OpenCV/StaticHelper( 9477):     Host:                        Linux 4.15.0-33-generic x86_64
I/OpenCV/StaticHelper( 9477):     Target:                      Linux 1 i686
I/OpenCV/StaticHelper( 9477):     CMake:                       2.8.12.2
I/OpenCV/StaticHelper( 9477):     CMake generator:             Ninja
I/OpenCV/StaticHelper( 9477):     CMake build tool:            /usr/bin/ninja
I/OpenCV/StaticHelper( 9477):     Configuration:               Release
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   CPU/HW features:
I/OpenCV/StaticHelper( 9477):     Baseline:                    SSE SSE2
I/OpenCV/StaticHelper( 9477):       requested:                 SSE2
I/OpenCV/StaticHelper( 9477):     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX
I/OpenCV/StaticHelper( 9477):       requested:                 SSE4_1 SSE4_2 AVX FP16
I/OpenCV/StaticHelper( 9477):       SSE4_1 (3 files):          + SSE3 SSSE3 SSE4_1
I/OpenCV/StaticHelper( 9477):       SSE4_2 (1 files):          + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2
I/OpenCV/StaticHelper( 9477):       FP16 (1 files):            + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
I/OpenCV/StaticHelper( 9477):       AVX (5 files):             + SSE3 SSSE3 SSE4_1 POPCNT SSE4_2 AVX
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   C/C++:
I/OpenCV/StaticHelper( 9477):     Built as dynamic libs?:      NO
I/OpenCV/StaticHelper( 9477):     C++ Compiler:                /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/x86-4.8/prebuilt/linux-x86_64/bin/i686-linux-android-g++ (ver 4.8)
I/OpenCV/StaticHelper( 9477):     C++ flags (Release):         -fexceptions -frtti -fpic --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-x86 -funwind-tables -funswitch-loops -finline-limit=300 -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=9   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -msse -msse2 -mfpmath=sse -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -O3 -DNDEBUG  -DNDEBUG
I/OpenCV/StaticHelper( 9477):     C++ flags (Debug):           -fexceptions -frtti -fpic --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-x86 -funwind-tables -funswitch-loops -finline-limit=300 -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=9   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -msse -msse2 -mfpmath=sse -fvisibility=hidden -fvisibility-inlines-hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
I/OpenCV/StaticHelper( 9477):     C Compiler:                  /usr/bin/ccache /opt/android/android-ndk-r10e/toolchains/x86-4.8/prebuilt/linux-x86_64/bin/i686-linux-android-gcc
I/OpenCV/StaticHelper( 9477):     C flags (Release):           -fexceptions -fpic --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-x86 -funwind-tables -funswitch-loops -finline-limit=300 -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=9   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -msse -msse2 -mfpmath=sse -fvisibility=hidden -fomit-frame-pointer -fstrict-aliasing -O3 -DNDEBUG  -DNDEBUG
I/OpenCV/StaticHelper( 9477):     C flags (Debug):             -fexceptions -fpic --sysroot=/opt/android/android-ndk-r10e/platforms/android-9/arch-x86 -funwind-tables -funswitch-loops -finline-limit=300 -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack  -DANDROID -D__ANDROID_API__=9   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-narrowing -Wno-comment -fdiagnostics-show-option -fomit-frame-pointer  -msse -msse2 -mfpmath=sse -fvisibility=hidden -fno-omit-frame-pointer -fno-strict-aliasing -O0 -g -DDEBUG -D_DEBUG  -DDEBUG -D_DEBUG
I/OpenCV/StaticHelper( 9477):     Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a  -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
I/OpenCV/StaticHelper( 9477):     Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a  -Wl,--no-undefined -Wl,--gc-sections -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now    
I/OpenCV/StaticHelper( 9477):     ccache:                      YES
I/OpenCV/StaticHelper( 9477):     Precompiled headers:         NO
I/OpenCV/StaticHelper( 9477):     Extra dependencies:          z dl m log
I/OpenCV/StaticHelper( 9477):     3rdparty dependencies:       libjpeg-turbo libwebp libpng libtiff libjasper IlmImf libprotobuf tbb libcpufeatures ittnotify ippiw ippicv
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   OpenCV modules:
I/OpenCV/StaticHelper( 9477):     To be built:                 calib3d core dnn features2d flann highgui imgcodecs imgproc java java_bindings_generator ml objdetect photo python_bindings_generator shape stitching superres video videoio videostab
I/OpenCV/StaticHelper( 9477):     Disabled:                    js world
I/OpenCV/StaticHelper( 9477):     Disabled by dependency:      -
I/OpenCV/StaticHelper( 9477):     Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev python2 python3 ts viz
I/OpenCV/StaticHelper( 9477):     Applications:                android_examples
I/OpenCV/StaticHelper( 9477):     Documentation:               NO
I/OpenCV/StaticHelper( 9477):     Non-free algorithms:         NO
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Android NDK:                   location: /opt/android/android-ndk-r10e
I/OpenCV/StaticHelper( 9477):     Android ABI:                 x86
I/OpenCV/StaticHelper( 9477):     NDK toolchain:               x86-4.8
I/OpenCV/StaticHelper( 9477):     STL type:                    gnustl_static
I/OpenCV/StaticHelper( 9477):     Native API level:            9
I/OpenCV/StaticHelper( 9477):   Android SDK:                   /opt/android/android-sdk-java7 (tools: 25.2.2 build tools: 23.0.3)
I/OpenCV/StaticHelper( 9477):     android tool:                /opt/android/android-sdk-java7/tools/android
I/OpenCV/StaticHelper( 9477):     SDK target:                  android-14
I/OpenCV/StaticHelper( 9477):     Projects build scripts:      Ant/Eclipse compatible
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   GUI: 
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Media I/O: 
I/OpenCV/StaticHelper( 9477):     ZLib:                        z (ver 1.2.3)
I/OpenCV/StaticHelper( 9477):     JPEG:                        build-libjpeg-turbo (ver 1.5.3-62)
I/OpenCV/StaticHelper( 9477):     WEBP:                        build (ver encoder: 0x020e)
I/OpenCV/StaticHelper( 9477):     PNG:                         build (ver 1.6.34)
I/OpenCV/StaticHelper( 9477):     TIFF:                        build (ver 42 - 4.0.9)
I/OpenCV/StaticHelper( 9477):     JPEG 2000:                   build (ver 1.900.1)
I/OpenCV/StaticHelper( 9477):     OpenEXR:                     build (ver 1.7.1)
I/OpenCV/StaticHelper( 9477):     HDR:                         YES
I/OpenCV/StaticHelper( 9477):     SUNRASTER:                   YES
I/OpenCV/StaticHelper( 9477):     PXM:                         YES
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Video I/O:
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Parallel framework:            TBB (ver 2018.0 interface 10001)
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Trace:                         YES (with Intel ITT)
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Other third-party libraries:
I/OpenCV/StaticHelper( 9477):     Intel IPP:                   2017.0.3 [2017.0.3]
I/OpenCV/StaticHelper( 9477):            at:                   /build/3_4_pack-android/build/o4a/3rdparty/ippicv/ippicv_lnx
I/OpenCV/StaticHelper( 9477):     Intel IPP IW:                sources (2017.0.3)
I/OpenCV/StaticHelper( 9477):               at:                /build/3_4_pack-android/build/o4a/3rdparty/ippicv/ippiw_lnx
I/OpenCV/StaticHelper( 9477):     Custom HAL:                  NO
I/OpenCV/StaticHelper( 9477):     Protobuf:                    build (3.5.1)
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Python (for build):            /usr/bin/python2.7
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Java:                          export all functions
I/OpenCV/StaticHelper( 9477):     ant:                         /usr/bin/ant (ver 1.9.3)
I/OpenCV/StaticHelper( 9477):     Java wrappers:               YES
I/OpenCV/StaticHelper( 9477):     Java tests:                  NO
I/OpenCV/StaticHelper( 9477): 
I/OpenCV/StaticHelper( 9477):   Install to:                    /build/3_4_pack-android/build/o4a/install
I/OpenCV/StaticHelper( 9477): -----------------------------------------------------------------
I/ScanPresenter( 9477): camera null
D/ScanPresenter( 9477): autofocus not available
E/SurfaceView( 9477): Exception configuring surface
E/SurfaceView( 9477): java.lang.RuntimeException: setParameters failed
E/SurfaceView( 9477): 	at android.hardware.Camera.native_setParameters(Native Method)
E/SurfaceView( 9477): 	at android.hardware.Camera.setParameters(Camera.java:2117)
E/SurfaceView( 9477): 	at com.sample.edgedetection.scan.ScanPresenter.initCamera(ScanPresenter.kt:139)
E/SurfaceView( 9477): 	at com.sample.edgedetection.scan.ScanPresenter.surfaceCreated(ScanPresenter.kt:144)
E/SurfaceView( 9477): 	at android.view.SurfaceView.updateSurface(SurfaceView.java:758)
E/SurfaceView( 9477): 	at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:155)
E/SurfaceView( 9477): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
E/SurfaceView( 9477): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2745)
E/SurfaceView( 9477): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
E/SurfaceView( 9477): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
E/SurfaceView( 9477): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
E/SurfaceView( 9477): 	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
E/SurfaceView( 9477): 	at android.view.Choreographer.doFrame(Choreographer.java:725)
E/SurfaceView( 9477): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
E/SurfaceView( 9477): 	at android.os.Handler.handleCallback(Handler.java:883)
E/SurfaceView( 9477): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/SurfaceView( 9477): 	at android.os.Looper.loop(Looper.java:214)
E/SurfaceView( 9477): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/SurfaceView( 9477): 	at java.lang.reflect.Method.invoke(Native Method)
E/SurfaceView( 9477): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/SurfaceView( 9477): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/EGL_emulation( 9477): eglMakeCurrent: 0xddc1a0c0: ver 2 0 (tinfo 0xddc0f720)
D/EGL_emulation( 9477): eglMakeCurrent: 0xddc1a0c0: ver 2 0 (tinfo 0xddc0f720)
D/EGL_emulation( 9477): eglMakeCurrent: 0xddc1a0c0: ver 2 0 (tinfo 0xddc0f720)
```

**Comment by sawankumarbundelkhandi** [comment]
The issue has been fixed with this PR - https://github.com/sawankumarbundelkhandi/edge_detection/pull/45

You can use it directly from Github in pubspec like
edge_detection:
    git: https://github.com/sawankumarbundelkhandi/edge_detection.git

I will update the plugin on pub soon.
