### ISSUE TITLE
Crash in release

### ISSUE THREAD

**Issue by omarsve** [sawankumarbundelkhandi/edge_detection#53]
Hi, my app in debug its working smoothly but when i release the app its crashing when I open the scanner

Flutter: v2.2.3
NDK: 21.4.7075529
Compile SDK Version: 30

`
2021-07-21 14:54:10.798 31887-31887/? D/OpenCV/StaticHelper: Trying to get library list
2021-07-21 14:54:10.801 31887-31887/? E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2021-07-21 14:54:10.801 31887-31887/? D/OpenCV/StaticHelper: Library list: ""
2021-07-21 14:54:10.801 31887-31887/? D/OpenCV/StaticHelper: First attempt to load libs
2021-07-21 14:54:10.801 31887-31887/? D/OpenCV/StaticHelper: Trying to init OpenCV libs
2021-07-21 14:54:10.801 31887-31887/? D/OpenCV/StaticHelper: Trying to load library opencv_java3
2021-07-21 14:54:10.809 2081-2298/? D/NetworkController.MobileSignalController(0/9): onDataActivity: direction=0
2021-07-21 14:54:10.809 2306-2509/? D/EPDG -- SIM0 [EpdgSubScription]: onDataActivity: direction=0
2021-07-21 14:54:10.811 2081-2081/? D/SecStatusBarMobileView: updateState: MobileIconState(subId=9, strengthId=2131232610, roaming=false, typeId=2131232468, roamingId=0, activityId=2131232640, slotId=0, visible=true)
2021-07-21 14:54:10.819 1446-1487/? E/Watchdog: !@Sync 661 [2021-07-21 14:54:10.819] FD count : 524, wdog_way : softdog
2021-07-21 14:54:10.820 31887-31887/? I/OpenCV: calling android_getCpuFeatures() ...
2021-07-21 14:54:10.821 31887-31887/? I/OpenCV: calling android_getCpuFeatures() ... Done (1f7ff)
2021-07-21 14:54:10.844 31887-31887/? D/OpenCV/StaticHelper: Library opencv_java3 loaded
2021-07-21 14:54:10.844 31887-31887/? D/OpenCV/StaticHelper: First attempt to load libs is OK
2021-07-21 14:54:10.845 31887-31887/? E/ansport.driver: No implementation found for java.lang.String i.a.b.a.b() (tried Java_i_a_b_a_b and Java_i_a_b_a_b__)
2021-07-21 14:54:10.847 31887-31887/? D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2021-07-21 14:54:10.848 31887-31887/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.robotransport.drivers, PID: 31887
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String i.a.b.a.b() (tried Java_i_a_b_a_b and Java_i_a_b_a_b__)
        at i.a.b.a.b(Native Method)
        at i.a.b.a.a(Unknown Source:0)
        at i.a.a.b.b(:2)
        at i.a.a.a.a(Unknown Source:1)
        at com.sample.edgedetection.scan.ScanActivity.n(Unknown Source:0)
        at c.m.a.f.a.onCreate(Unknown Source:23)
        at android.app.Activity.performCreate(Activity.java:7957)
        at android.app.Activity.performCreate(Activity.java:7946)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
2021-07-21 14:54:10.852 1446-6167/? D/DeviceReportingSecurityChecker: mIsICDStatus === true mIsTmoSim == true mIsMyAccountSignature== true
2021-07-21 14:54:10.852 1446-1491/? D/ActivityManager: TMO APP_STATE_BROADCAST_STOP_MSG
2021-07-21 14:54:10.852 1446-1491/? D/AppStateBroadcaster: sendApplicationStop(com.demo.app, 31887, 3) called from com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2099)
2021-07-21 14:54:10.852 1446-32017/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2`

**Comment by gamalielCastro** [comment]
is the same as issue #20

**Comment by omarsve** [comment]
> is the same as issue #20

Its not the same issue because there it gets 
`D/OpenCV/StaticHelper( 3440): Cannot load library "opencv_java3"
`

and in my case the library loads just fine
`2021-07-21 14:54:10.844 31887-31887/? D/OpenCV/StaticHelper: Library opencv_java3 loaded
`

**Comment by kiwinam** [comment]
Hi, I had the same symptoms as you, but I just came back from fixing it and I'm going to let you know.
If you only have crash in release, aren't you using prograud?

I think I can't get the necessary method from edge_detection because I obfuscate the method in Progard and obfuscate the native method.
So I solved this problem with a few settings.

1. Add this code line under android > app > proguard-rules.pro
```
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}
```

2. Add this code line under anroid > app > build.gradle.
```
android {
 ...
    buildTypes {
     release {
                minifyEnabled true

                proguardFile getDefaultProguardFile('proguard-android.txt')
                // Proguard settings needed for the project.
                proguardFile 'proguard-rules.pro'
            }
    }
}
```

I hope my answer will help those who have similar problems with us.

Bye, everyone.

**Comment by Rezki-Pratama** [comment]
> Hi, I had the same symptoms as you, but I just came back from fixing it and I'm going to let you know. If you only have crash in release, aren't you using prograud?
> 
> I think I can't get the necessary method from edge_detection because I obfuscate the method in Progard and obfuscate the native method. So I solved this problem with a few settings.
> 
> 1. Add this code line under android > app > proguard-rules.pro
> 
> ```
> -keepclasseswithmembernames,includedescriptorclasses class * {
>     native <methods>;
> }
> ```
> 
>  2. Add this code line under anroid > app > build.gradle.
> 
> ```
> android {
>  ...
>     buildTypes {
>      release {
>                 minifyEnabled true
> 
>                 proguardFile getDefaultProguardFile('proguard-android.txt')
>                 // Proguard settings needed for the project.
>                 proguardFile 'proguard-rules.pro'
>             }
>     }
> }
> ```
> 
> I hope my answer will help those who have similar problems with us.
> 
> Bye, everyone.

if I change minifyEnabled false its work for me

**Comment by azaderdogan** [comment]
> Hi, I had the same symptoms as you, but I just came back from fixing it and I'm going to let you know. If you only have crash in release, aren't you using prograud?
> 
> I think I can't get the necessary method from edge_detection because I obfuscate the method in Progard and obfuscate the native method. So I solved this problem with a few settings.
> 
> 1. Add this code line under android > app > proguard-rules.pro
> 
> ```
> -keepclasseswithmembernames,includedescriptorclasses class * {
>     native <methods>;
> }
> ```
> 
> 2. Add this code line under anroid > app > build.gradle.
> 
> ```
> android {
>  ...
>     buildTypes {
>      release {
>                 minifyEnabled true
> 
>                 proguardFile getDefaultProguardFile('proguard-android.txt')
>                 // Proguard settings needed for the project.
>                 proguardFile 'proguard-rules.pro'
>             }
>     }
> }
> ```
> 
> I hope my answer will help those who have similar problems with us.
> 
> Bye, everyone.

thanks.

**Comment by sawankumarbundelkhandi** [comment]
@omarsve if this answer https://github.com/sawankumarbundelkhandi/edge_detection/issues/53#issuecomment-944052647 helped you please close this issue.

**Comment by Mahdi-IvI** [comment]
Hi, I had the same problem but, what helped me was:
1. Add this code line under android > app > proguard-rules.pro

```
-keep class org.xmlpull.v1.** { *; },
```

2.  Add this code line under android > app > build.gradle.

```
android {
 ...
    buildTypes {
     release {
                minifyEnabled true
                proguardFile getDefaultProguardFile('proguard-android.txt')
                proguardFile 'proguard-rules.pro'
                ...
            }
    }
}
```

**What Does It Do?**

This ProGuard/R8 rule ensures that all classes inside the org.xmlpull.v1 package are preserved as they are.

**What This Rule Does**
	•	The -keep directive prevents R8 from modifying, renaming, or removing any classes inside the org.xmlpull.v1 package.
	•	{ *; } means keep all methods and fields inside these classes.
	•	This ensures that the edge-detection package can still find and use these XML classes correctly in release mode.

Thanks @kiwinam
