### ISSUE TITLE
Croping Screen is crashing which is causing app to crash when selecting particular image. 

### ISSUE THREAD

**Issue by kamran8545** [sawankumarbundelkhandi/edge_detection#75]
**Here is the image which causing it to crash.**

1. https://drive.google.com/file/d/1vxj_d4mrPjg0BPqozcdQ6R3t7JvM84gn/view?usp=sharing

**I have traced this issues in scan/ScanActivity.kt on function onImageSelected(), on line mPresenter.detectEdge(pic); 
it is getting crashed. Here is the exception that I am getting while selection image.**  

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://media/external/images/media/5934 flg=0x1 (has extras) }} to activity {com.example.spsu/com.sample.edgedetection.scan.ScanActivity}: CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
E/AndroidRuntime(19067): ]
E/AndroidRuntime(19067): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5230)
E/AndroidRuntime(19067): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5271)
E/AndroidRuntime(19067): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(19067): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(19067): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(19067): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
E/AndroidRuntime(19067): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(19067): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(19067): 	at android.app.ActivityThread.main(ActivityThread.java:7948)
E/AndroidRuntime(19067): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19067): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(19067): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(19067): Caused by: CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/imgproc/src/color.cpp:10638: error: (-215) scn == 3 || scn == 4 in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
E/AndroidRuntime(19067): ]
E/AndroidRuntime(19067): 	at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
E/AndroidRuntime(19067): 	at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:1826)
E/AndroidRuntime(19067): 	at com.sample.edgedetection.processor.PaperProcessorKt.findContours(PaperProcessor.kt:88)
E/AndroidRuntime(19067): 	at com.sample.edgedetection.processor.PaperProcessorKt.processPicture(PaperProcessor.kt:15)
E/AndroidRuntime(19067): 	at com.sample.edgedetection.scan.ScanPresenter.detectEdge(ScanPresenter.kt:206)
E/AndroidRuntime(19067): 	at com.sample.edgedetection.scan.ScanActivity.onImageSelected(ScanActivity.kt:234)
E/AndroidRuntime(19067): 	at com.sample.edgedetection.scan.ScanActivity.onActivityResult(ScanActivity.kt:188)
E/AndroidRuntime(19067): 	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
E/AndroidRuntime(19067): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5223)
E/AndroidRuntime(19067): 	... 11 more

**Comment by sawankumarbundelkhandi** [comment]
@kamran8545 I am not sure but maybe the image that you are cropping itself is very small.

**Comment by kamran8545** [comment]
Yes it is very small. but you handle it by catching exception. It is
occuring in ScanActivity.kt in onImageSelected() in line
mPresenter.detectEdge(pic);.

You can handle it here or you can handle where it is causing it.
