### ISSUE TITLE
Sometimes error when scan image from any folder in Android

### ISSUE THREAD

**Issue by saelco** [sawankumarbundelkhandi/edge_detection#82]
I scan image from a folder and everything is ok. But when I scan image from another folder like Screenshoots folder, I get error like it:

I/ExifInterface_JNI( 5112): Raw image not detected
W/ExifInterface( 5112): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface( 5112): java.io.IOException: Invalid marker: 89
W/ExifInterface( 5112): 	at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1885)
W/ExifInterface( 5112): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1517)
W/ExifInterface( 5112): 	at android.media.ExifInterface.<init>(ExifInterface.java:1216)
W/ExifInterface( 5112): 	at com.sample.edgedetection.scan.ScanActivity.onImageSelected(ScanActivity.kt:206)
W/ExifInterface( 5112): 	at com.sample.edgedetection.scan.ScanActivity.onActivityResult(ScanActivity.kt:187)
W/ExifInterface( 5112): 	at android.app.Activity.dispatchActivityResult(Activity.java:7010)
W/ExifInterface( 5112): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4183)
W/ExifInterface( 5112): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4230)
W/ExifInterface( 5112): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
W/ExifInterface( 5112): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
W/ExifInterface( 5112): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/ExifInterface( 5112): 	at android.os.Looper.loop(Looper.java:154)
W/ExifInterface( 5112): 	at android.app.ActivityThread.main(ActivityThread.java:6312)
W/ExifInterface( 5112): 	at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface( 5112): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
W/ExifInterface( 5112): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
I/ScanActivity( 5112): rotation:-1
I/ScanActivity( 5112): width:0.0
I/ScanActivity( 5112): height:0.0
E/cv::error()( 5112): OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in void* cv::imdecode_(const cv::Mat&, int, int, cv::Mat*), file /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp, line 637
E/org.opencv.imgcodecs( 5112): imgcodecs::imdecode_10() caught cv::Exception: /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp:637: error: (-215) !buf.empty() && buf.isContinuous() in function void* cv::imdecode_(const cv::Mat&, int, int, cv::Mat*)
D/AndroidRuntime( 5112): Shutting down VM
E/AndroidRuntime( 5112): FATAL EXCEPTION: main
E/AndroidRuntime( 5112): Process: my.project.scan, PID: 5112
E/AndroidRuntime( 5112): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://media/external/images/media/1180364 flg=0x1 }} to activity {my.project.scan/com.sample.edgedetection.scan.ScanActivity}: CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp:637: error: (-215) !buf.empty() && buf.isContinuous() in function void* cv::imdecode_(const cv::Mat&, int, int, cv::Mat*)
E/AndroidRuntime( 5112): ]
E/AndroidRuntime( 5112): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4187)
E/AndroidRuntime( 5112): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4230)
E/AndroidRuntime( 5112): 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
E/AndroidRuntime( 5112): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1584)
E/AndroidRuntime( 5112): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5112): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 5112): 	at android.app.ActivityThread.main(ActivityThread.java:6312)
E/AndroidRuntime( 5112): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5112): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
E/AndroidRuntime( 5112): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
E/AndroidRuntime( 5112): Caused by: CvException [org.opencv.core.CvException: cv::Exception: /build/master_pack-android/opencv/modules/imgcodecs/src/loadsave.cpp:637: error: (-215) !buf.empty() && buf.isContinuous() in function void* cv::imdecode_(const cv::Mat&, int, int, cv::Mat*)
E/AndroidRuntime( 5112): ]
E/AndroidRuntime( 5112): 	at org.opencv.imgcodecs.Imgcodecs.imdecode_0(Native Method)
E/AndroidRuntime( 5112): 	at org.opencv.imgcodecs.Imgcodecs.imdecode(Imgcodecs.java:95)
E/AndroidRuntime( 5112): 	at com.sample.edgedetection.scan.ScanActivity.onImageSelected(ScanActivity.kt:230)
E/AndroidRuntime( 5112): 	at com.sample.edgedetection.scan.ScanActivity.onActivityResult(ScanActivity.kt:187)
E/AndroidRuntime( 5112): 	at android.app.Activity.dispatchActivityResult(Activity.java:7010)
E/AndroidRuntime( 5112): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4183)
E/AndroidRuntime( 5112): 	... 9 more

How to solve this problem?

**Comment by somarok** [comment]
I've same problem. Is there anyone fixed this problem?

**Comment by duypxd** [comment]
[Solution](https://github.com/sawankumarbundelkhandi/edge_detection/issues/123)
